name:                blah-hs
version:             0.1.0.0
github:              "githubuser/blah-hs"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2023 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/blah-hs#readme>

dependencies:
- base >= 4.7 && < 5

default-extensions:
  - AllowAmbiguousTypes
  - DataKinds
  - DeriveGeneric
  - DeriveAnyClass 
  - DerivingStrategies
  - KindSignatures
  - UndecidableInstances
  - DefaultSignatures
  - FlexibleContexts
  - TypeOperators
  - PolyKinds
  - FlexibleInstances
  - TemplateHaskell

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  blah-hs-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - blah-hs

tests:
  blah-hs-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - blah-hs
